services:
  - type: web
    name: patentai-backend
    runtime: python
    plan: starter
    rootDir: ./backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000 --workers 2
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/backend

  - type: web
    name: patentai-frontend
    runtime: python
    plan: starter
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port 10001 --server.address 0.0.0.0
    envVars:
      - key: GROQ_API_KEY
        sync: false
