services:
  - type: web
    name: patentai-backend
    env: python
    plan: starter
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python startup.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ENV
        value: dev # Use 'prod' in production to tighten CORS later

  - type: web
    name: patentai-frontend
    env: python
    plan: starter
    rootDir: frontend
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: https://patentai-backend.onrender.com # Matches your backend service name
      - key: GROQ_API_KEY
        sync: false
      - key: ENV
        value: dev
