services:
  - type: web
    name: patentai-backend
    env: python
    repo: https://github.com/MasterCoderKay/patent-ai
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=8000
    envVars:
      - key: GROQ_API_KEY
        sync: false
    rootDir: backend
