services:
  - type: web
    name: patentai-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GROQ_API_KEY
        value: your_real_groq_api_key

  - type: web
    name: patentai-frontend
    env: python
    buildCommand: pip install -r backend/requirements.txt && pip install streamlit
    startCommand: streamlit run streamlit_app.py --server.port 10001 --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: https://patentai-backend.onrender.com
